# Generated by Django 5.2.7 on 2025-10-01 16:08

import django.db.models.deletion
import django.utils.timezone
import ecommerce.models.product
import ecommerce.models.product_image
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryServiceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('config', models.JSONField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ecommerce_delivery_service_providers',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'db_table': 'ecommerce_districts',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('start', models.DateTimeField(blank=True)),
                ('end', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'ecommerce_promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'db_table': 'ecommerce_provinces',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20, null=True)),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, 'Deactive'), (1, 'Active')], default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ecommerce_customers',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='ecommerce.customer')),
            ],
            options={
                'db_table': 'ecommerce_carts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistrictMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('delivery_service_provider', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_maping', to='ecommerce.deliveryserviceprovider')),
                ('district', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_maping', to='ecommerce.district')),
            ],
            options={
                'db_table': 'ecommerce_district_maping',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='mapping',
            field=models.ManyToManyField(blank=True, null=True, related_name='districts', through='ecommerce.DistrictMapping', to='ecommerce.deliveryserviceprovider'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('tax_code', models.CharField(max_length=15)),
                ('payment_method', models.SmallIntegerField(blank=True, choices=[(0, 'Bank transfer'), (1, 'Cash on delivery')], default=0)),
                ('payment_status', models.SmallIntegerField(blank=True, choices=[(0, 'Initiated'), (1, 'Pending'), (2, 'Authorized'), (3, 'Captured'), (4, 'Completed'), (5, 'Refused/Declined'), (6, 'Error'), (7, 'Canceled'), (8, 'Settled')], default=0)),
                ('account_number', models.CharField(max_length=15)),
                ('vat_rate', models.FloatField(blank=True, default=0.0)),
                ('shipping_fee', models.FloatField(blank=True, default=0.0)),
                ('shipping_status', models.SmallIntegerField(blank=True, choices=[(0, 'Initiated'), (1, 'Pending'), (2, 'Authorized'), (3, 'Captured'), (4, 'Completed'), (5, 'Refused/Declined'), (6, 'Error'), (7, 'Canceled'), (8, 'Settled')], default=0)),
                ('date', models.DateField(null=True)),
                ('customer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ecommerce.customer')),
            ],
            options={
                'db_table': 'ecommerce_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to=ecommerce.models.product.product_image_path)),
                ('price', models.FloatField(blank=True, default=0.0)),
                ('in_stock', models.FloatField(blank=True, default=0.0)),
                ('weight', models.FloatField(blank=True, default=0.0)),
                ('length', models.FloatField(blank=True, default=0.0)),
                ('width', models.FloatField(blank=True, default=0.0)),
                ('height', models.FloatField(blank=True, default=0.0)),
                ('tax_rate', models.FloatField(blank=True, default=0.0)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_descriptions', to='contents.longcontent')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_names', to='contents.shortcontent')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_units', to='contents.shortcontent')),
            ],
            options={
                'db_table': 'ecommerce_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.TextField(blank=True, max_length=255)),
                ('unit', models.TextField(blank=True, max_length=255)),
                ('quantity', models.FloatField(blank=True, default=0.0)),
                ('price', models.FloatField(blank=True, default=0.0)),
                ('amount', models.FloatField(blank=True, default=0.0)),
                ('order', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product')),
            ],
            options={
                'db_table': 'ecommerce_order_items',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField(blank=True, default=0.0)),
                ('origin_price', models.FloatField(blank=True, default=0.0)),
                ('selected', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ecommerce.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.product')),
            ],
            options={
                'db_table': 'ecommerce_cart_items',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category_names', to='contents.shortcontent')),
            ],
            options={
                'db_table': 'ecommerce_product_categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='ecommerce.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=ecommerce.models.product_image.product_image_path)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerce.product')),
            ],
            options={
                'db_table': 'ecommerce_product_images',
            },
        ),
        migrations.CreateModel(
            name='PromotionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_limit', models.FloatField(blank=True, default=0.0)),
                ('quantity_limit_by_customer', models.FloatField(blank=True, default=0.0)),
                ('discount', models.FloatField(blank=True, default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_items', to='ecommerce.product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_items', to='ecommerce.promotion')),
            ],
            options={
                'db_table': 'ecommerce_promotion_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='promotions', through='ecommerce.PromotionItem', to='ecommerce.product'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='ecommerce.province'),
        ),
        migrations.CreateModel(
            name='ProvinceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('delivery_service_provider', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_maping', to='ecommerce.deliveryserviceprovider')),
                ('province', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='maping', to='ecommerce.province')),
            ],
            options={
                'db_table': 'ecommerce_province_maping',
            },
        ),
        migrations.AddField(
            model_name='province',
            name='mapping',
            field=models.ManyToManyField(blank=True, null=True, related_name='provinces', through='ecommerce.ProvinceMapping', to='ecommerce.deliveryserviceprovider'),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('district', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='ecommerce.district')),
            ],
            options={
                'db_table': 'ecommerce_wards',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_addresses', to='ecommerce.customer')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_addresses', to='ecommerce.district')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_addresses', to='ecommerce.province')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_addresses', to='ecommerce.ward')),
            ],
            options={
                'db_table': 'ecommerce_shipping_addresses',
            },
        ),
        migrations.CreateModel(
            name='WardMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('delivery_service_provider', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward_maping', to='ecommerce.deliveryserviceprovider')),
                ('ward', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward_maping', to='ecommerce.ward')),
            ],
            options={
                'db_table': 'ecommerce_ward_maping',
            },
        ),
        migrations.AddField(
            model_name='ward',
            name='mapping',
            field=models.ManyToManyField(blank=True, null=True, related_name='wards', through='ecommerce.WardMapping', to='ecommerce.deliveryserviceprovider'),
        ),
    ]
