# Generated by Django 5.2.7 on 2025-10-01 16:08

import django.db.models.deletion
import django.utils.timezone
import knowledge.models.namespace
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to=knowledge.models.namespace.logo_path)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('access', models.SmallIntegerField(blank=True, choices=[(0, 'Private'), (1, 'Internal'), (2, 'Public')], default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_namespaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_namespaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('namespace', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_page', to='knowledge.namespace')),
            ],
            options={
                'db_table': 'knowledge_home_pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NamespaceMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespace_memebers', to='businesses.employee')),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespace_memebers', to='knowledge.namespace')),
            ],
            options={
                'db_table': 'knowledge_namespace_members',
            },
        ),
        migrations.AddField(
            model_name='namespace',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='namespaces', through='knowledge.NamespaceMember', to='businesses.employee'),
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=255, null=True)),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('namespace', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='knowledge.namespace')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.page')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'db_table': 'knowledge_pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='namespace',
            index=models.Index(fields=['slug'], name='knowledge_n_slug_4724d8_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['slug'], name='knowledge_p_slug_6112f2_idx'),
        ),
    ]
