# Generated by Django 4.2.25 on 2025-10-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_subjects_credit_hours_subjects_fee_per_credit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='fee_per_credit',
            field=models.DecimalField(decimal_places=2, default=500000, max_digits=10),
        ),
    ]
