# Generated by Django 4.2.25 on 2025-10-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_alter_subjects_fee_per_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='description_file',
            field=models.FileField(blank=True, null=True, upload_to='subject_descriptions/'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='subject_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
