# Generated by Django 4.2.7 on 2025-11-17 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_subjects_description_subjects_description_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDescriptionFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='subject_descriptions/')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_files', to='student_management_app.subjects')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
