# Generated by Django 5.0.4 on 2025-10-03 12:58

import django.db.models.deletion
import django.utils.timezone
import uuid
import websites.models.article
import websites.models.build
import websites.models.site
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, unique=True, verbose_name='Tên lớp')),
                ('major', models.CharField(max_length=50, verbose_name='Ngành')),
                ('year', models.CharField(max_length=10, verbose_name='Khóa')),
                ('teacher_name', models.CharField(max_length=100, verbose_name='Giảng viên chủ nhiệm')),
                ('room', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phòng học')),
                ('student_count', models.IntegerField(default=0, verbose_name='Số sinh viên')),
                ('status', models.CharField(choices=[('Đang hoạt động', 'Đang hoạt động'), ('Tạm dừng', 'Tạm dừng'), ('Kết thúc', 'Kết thúc')], default='Đang hoạt động', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'ordering': ['class_name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('target_role', models.CharField(choices=[('Toàn trường', 'Toàn trường'), ('Khoa CNTT', 'Khoa CNTT'), ('Khoa KTPM', 'Khoa KTPM'), ('Khoa ATTT', 'Khoa ATTT'), ('CNTT21A', 'Lớp CNTT21A'), ('CNTT21B', 'Lớp CNTT21B')], default='Toàn trường', max_length=50, verbose_name='Đối tượng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'websites_sections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('department', models.CharField(choices=[('Phòng đào tạo', 'Phòng đào tạo'), ('Phòng công tác sinh viên', 'Phòng công tác sinh viên')], max_length=50, verbose_name='Phòng ban')),
                ('role', models.CharField(choices=[('Training Staff', 'Nhân viên phòng đào tạo'), ('Student Affairs Staff', 'Nhân viên phòng công tác sinh viên')], max_length=50, verbose_name='Vai trò')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'ordering': ['staff_id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, unique=True, verbose_name='Mã môn học')),
                ('subject_name', models.CharField(max_length=100, verbose_name='Tên môn học')),
                ('credits', models.IntegerField(verbose_name='Số tín chỉ')),
                ('major', models.CharField(max_length=50, verbose_name='Ngành')),
                ('type', models.CharField(choices=[('Bắt buộc', 'Bắt buộc'), ('Tự chọn', 'Tự chọn'), ('Thực tập', 'Thực tập')], default='Bắt buộc', max_length=20, verbose_name='Loại môn')),
                ('semester', models.CharField(max_length=10, verbose_name='Học kỳ')),
                ('teacher_name', models.CharField(max_length=100, verbose_name='Giảng viên')),
                ('status', models.CharField(choices=[('Đang mở', 'Đang mở'), ('Tạm đóng', 'Tạm đóng'), ('Kết thúc', 'Kết thúc')], default='Đang mở', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'ordering': ['subject_code'],
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=255, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_category_names', to='contents.shortcontent')),
            ],
            options={
                'db_table': 'websites_article_categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=250)),
                ('keywords', models.CharField(blank=True, max_length=250)),
                ('thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to=websites.models.article.article_thumbnail_path)),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, 'Draft'), (1, 'Published'), (2, 'Un-published')], default=0)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_contents', to='contents.longcontent')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_descriptions', to='contents.shortcontent')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_titles', to='contents.shortcontent')),
                ('categories', models.ManyToManyField(blank=True, null=True, related_name='articles', to='websites.articlecategory')),
            ],
            options={
                'db_table': 'websites_articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.article')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.section')),
            ],
            options={
                'db_table': 'websites_section_acticles',
            },
        ),
        migrations.AddField(
            model_name='section',
            name='articles',
            field=models.ManyToManyField(blank=True, null=True, related_name='sections', through='websites.SectionArticle', to='websites.article'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.FileField(blank=True, max_length=255, null=True, upload_to=websites.models.site.website_icon_path)),
                ('template', models.FileField(blank=True, max_length=255, null=True, upload_to=websites.models.site.website_template_path)),
                ('template_settings', models.JSONField(blank=True, null=True)),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, 'Draft'), (1, 'Published'), (2, 'Un-published')], default=0)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_descriptions', to='contents.shortcontent')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_titles', to='contents.shortcontent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='section',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='websites.site'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=250)),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, 'Draft'), (1, 'Published'), (2, 'Un-published')], default=0)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_contents', to='contents.longcontent')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_descriptions', to='contents.shortcontent')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_titles', to='contents.shortcontent')),
                ('site', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='websites.site')),
            ],
            options={
                'db_table': 'websites_routes',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='websites.menu')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_menu_titles', to='contents.shortcontent')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='websites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.FileField(blank=True, max_length=255, null=True, upload_to=websites.models.build.website_archive_path)),
                ('status', models.SmallIntegerField(blank=True, choices=[(0, 'Open'), (1, 'Scheduling'), (2, 'In-progress'), (3, 'Processed'), (4, 'Deployed'), (5, 'Failed')], default=0)),
                ('info', models.JSONField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('site', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='websites.site')),
            ],
            options={
                'db_table': 'websites_builds',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='sites',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='websites.site'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Mã sinh viên')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('major', models.CharField(max_length=50, verbose_name='Ngành')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Ảnh đại diện')),
                ('status', models.CharField(choices=[('Đang học', 'Đang học'), ('Tốt nghiệp', 'Tốt nghiệp'), ('Tạm nghỉ', 'Tạm nghỉ')], default='Đang học', max_length=20, verbose_name='Trạng thái')),
                ('gpa', models.FloatField(default=0.0, verbose_name='Điểm TB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='websites.classroom', verbose_name='Lớp')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản người dùng')),
            ],
            options={
                'verbose_name': 'Sinh viên',
                'verbose_name_plural': 'Sinh viên',
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Khen thưởng', 'Khen thưởng'), ('Kỷ luật', 'Kỷ luật')], max_length=20, verbose_name='Loại')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('status', models.CharField(choices=[('Đang xử lý', 'Đang xử lý'), ('Đã xử lý', 'Đã xử lý')], default='Đang xử lý', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.student', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Khen thưởng & Kỷ luật',
                'verbose_name_plural': 'Khen thưởng & Kỷ luật',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10, verbose_name='Học kỳ')),
                ('registered_credits', models.IntegerField(verbose_name='Số tín chỉ đăng ký')),
                ('tuition_per_credit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Học phí/tín chỉ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='websites.student', verbose_name='Sinh viên')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='websites.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Đăng ký học phần',
                'verbose_name_plural': 'Đăng ký học phần',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10, verbose_name='Học kỳ')),
                ('midterm_score', models.FloatField(default=0.0, verbose_name='Điểm giữa kỳ')),
                ('final_score', models.FloatField(default=0.0, verbose_name='Điểm cuối kỳ')),
                ('gpa', models.FloatField(default=0.0, verbose_name='Điểm TB')),
                ('status', models.CharField(choices=[('Hoàn thành', 'Hoàn thành'), ('Chưa hoàn thành', 'Chưa hoàn thành'), ('Thi lại', 'Thi lại')], default='Chưa hoàn thành', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.student', verbose_name='Sinh viên')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Điểm số',
                'verbose_name_plural': 'Điểm số',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Ảnh đại diện')),
                ('teacher_id', models.CharField(max_length=20, unique=True, verbose_name='Mã giảng viên')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('department', models.CharField(choices=[('CNTT', 'Khoa CNTT'), ('KTPM', 'Khoa KTPM'), ('ATTT', 'Khoa ATTT')], max_length=50, verbose_name='Khoa')),
                ('status', models.CharField(choices=[('Đang làm việc', 'Đang làm việc'), ('Nghỉ hưu', 'Nghỉ hưu'), ('Tạm nghỉ', 'Tạm nghỉ')], default='Đang làm việc', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='websites.subject', verbose_name='Môn giảng dạy')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản người dùng')),
            ],
            options={
                'verbose_name': 'Giảng viên',
                'verbose_name_plural': 'Giảng viên',
                'ordering': ['teacher_id'],
            },
        ),
        migrations.CreateModel(
            name='Tuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Số tiền')),
                ('semester', models.CharField(max_length=10, verbose_name='Học kỳ')),
                ('due_date', models.DateField(verbose_name='Hạn đóng')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ngày đóng')),
                ('status', models.CharField(choices=[('Chưa đóng', 'Chưa đóng'), ('Đã đóng', 'Đã đóng'), ('Quá hạn', 'Quá hạn')], default='Chưa đóng', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuitions', to='websites.registration', verbose_name='Đăng ký học phần')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.student', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Học phí',
                'verbose_name_plural': 'Học phí',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='articlecategory',
            index=models.Index(fields=['slug'], name='websites_ar_slug_7ea674_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['name'], name='websites_se_name_94aaa6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('site', 'name')},
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['path'], name='websites_ro_path_629ddf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('site', 'path')},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='websites_ar_slug_32cc9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student', 'subject', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'semester')},
        ),
    ]
