# Generated by Django 5.0.4 on 2025-09-30 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_classroom_notification_staff_student_subject_teacher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['class_name'], 'verbose_name': 'Lớp học', 'verbose_name_plural': 'Lớp học'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['staff_id'], 'verbose_name': 'Nhân viên', 'verbose_name_plural': 'Nhân viên'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'verbose_name': 'Sinh viên', 'verbose_name_plural': 'Sinh viên'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_code'], 'verbose_name': 'Môn học', 'verbose_name_plural': 'Môn học'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['teacher_id'], 'verbose_name': 'Giảng viên', 'verbose_name_plural': 'Giảng viên'},
        ),
        migrations.AlterUniqueTogether(
            name='tuition',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='level',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='title',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='position',
        ),
        migrations.AddField(
            model_name='grade',
            name='gpa',
            field=models.FloatField(default=0.0, verbose_name='Điểm TB'),
        ),
        migrations.AddField(
            model_name='grade',
            name='status',
            field=models.CharField(choices=[('Hoàn thành', 'Hoàn thành'), ('Chưa hoàn thành', 'Chưa hoàn thành'), ('Thi lại', 'Thi lại')], default='Chưa hoàn thành', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_role',
            field=models.CharField(choices=[('Toàn trường', 'Toàn trường'), ('Khoa CNTT', 'Khoa CNTT'), ('Khoa KTPM', 'Khoa KTPM'), ('Khoa ATTT', 'Khoa ATTT'), ('CNTT21A', 'Lớp CNTT21A'), ('CNTT21B', 'Lớp CNTT21B')], default='Toàn trường', max_length=50, verbose_name='Đối tượng'),
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='websites.classroom', verbose_name='Lớp'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='students/profile_pictures/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản người dùng'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teachers/profile_pictures/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='websites.subject', verbose_name='Môn giảng dạy'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản người dùng'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='student_count',
            field=models.IntegerField(default=0, verbose_name='Số sinh viên'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='final_score',
            field=models.FloatField(default=0.0, verbose_name='Điểm cuối kỳ'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='midterm_score',
            field=models.FloatField(default=0.0, verbose_name='Điểm giữa kỳ'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='semester',
            field=models.CharField(max_length=10, verbose_name='Học kỳ'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='status',
            field=models.CharField(choices=[('Đang xử lý', 'Đang xử lý'), ('Đã xử lý', 'Đã xử lý')], default='Đang xử lý', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('Phòng đào tạo', 'Phòng đào tạo'), ('Phòng công tác sinh viên', 'Phòng công tác sinh viên')], max_length=50, verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Training Staff', 'Nhân viên phòng đào tạo'), ('Student Affairs Staff', 'Nhân viên phòng công tác sinh viên')], max_length=50, verbose_name='Vai trò'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Đang học', 'Đang học'), ('Tốt nghiệp', 'Tốt nghiệp'), ('Tạm nghỉ', 'Tạm nghỉ')], default='Đang học', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.IntegerField(verbose_name='Số tín chỉ'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(max_length=10, verbose_name='Học kỳ'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('Đang mở', 'Đang mở'), ('Tạm đóng', 'Tạm đóng'), ('Kết thúc', 'Kết thúc')], default='Đang mở', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('Bắt buộc', 'Bắt buộc'), ('Tự chọn', 'Tự chọn'), ('Thực tập', 'Thực tập')], default='Bắt buộc', max_length=20, verbose_name='Loại môn'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('CNTT', 'Khoa CNTT'), ('KTPM', 'Khoa KTPM'), ('ATTT', 'Khoa ATTT')], max_length=50, verbose_name='Khoa'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default=1, max_length=15, verbose_name='Số điện thoại'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('Đang làm việc', 'Đang làm việc'), ('Nghỉ hưu', 'Nghỉ hưu'), ('Tạm nghỉ', 'Tạm nghỉ')], default='Đang làm việc', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='due_date',
            field=models.DateField(verbose_name='Hạn đóng'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày đóng'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='semester',
            field=models.CharField(max_length=10, verbose_name='Học kỳ'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='status',
            field=models.CharField(choices=[('Chưa đóng', 'Chưa đóng'), ('Đã đóng', 'Đã đóng'), ('Quá hạn', 'Quá hạn')], default='Chưa đóng', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='tuition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='classroom',
            table=None,
        ),
        migrations.AlterModelTable(
            name='grade',
            table=None,
        ),
        migrations.AlterModelTable(
            name='notification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reward',
            table=None,
        ),
        migrations.AlterModelTable(
            name='staff',
            table=None,
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subject',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teacher',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tuition',
            table=None,
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10, verbose_name='Học kỳ')),
                ('registered_credits', models.IntegerField(verbose_name='Số tín chỉ đăng ký')),
                ('tuition_per_credit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Học phí/tín chỉ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='websites.student', verbose_name='Sinh viên')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='websites.subject', verbose_name='Môn học')),
            ],
            options={
                'verbose_name': 'Đăng ký học phần',
                'verbose_name_plural': 'Đăng ký học phần',
                'unique_together': {('student', 'subject', 'semester')},
            },
        ),
        migrations.AddField(
            model_name='tuition',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuitions', to='websites.registration', verbose_name='Đăng ký học phần'),
        ),
    ]
