# Generated by Django 5.0.4 on 2025-10-02 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
    ]
