# Generated by Django 5.0.4 on 2025-09-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, to='oauth.role', verbose_name='Vai trò'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Giảng viên'), ('student', 'Sinh viên'), ('training_staff', 'Nhân viên phòng đào tạo'), ('student_affairs', 'Nhân viên phòng công tác sinh viên')], default='student', max_length=20, verbose_name='Loại người dùng'),
        ),
    ]
