# Generated by Django 5.0.4 on 2025-10-04 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_accesstoken_checksum'),
        ('oauth', '0002_user_profile_picture_user_roles_user_user_type'),
    ]

    operations = [
    ]
